### ISSUE TITLE
Refact

### ISSUE THREAD

**Issue by Alexey-T** [hudochenkov/ecsstractor#1]
hi. Is it possible to refactor? to have `def` which makes css file from `text` str variable (EOL separated text of file).

So i can port to Synwrite

**Comment by hudochenkov** [comment]
I see no point to do this in this repository. I've made [gist](https://gist.github.com/hudochenkov/d0271b9ded49f5dac1a4) for you so you can see what need to change. Gist contains already changed code for your needs. In revisions you can see what changed.

**Comment by Alexey-T** [comment]
Thank , though not easy to find how to convert text to css

**Comment by hudochenkov** [comment]
What's a trouble?

**Comment by Alexey-T** [comment]
what function to call? if i want for `text` get the css file.

**Comment by hudochenkov** [comment]
Still don't understand what you want to know :(

There is how plugin is works:

1. When `run` command is called from editor, plugin get selection or whole file in `self.source` variable.
2. Depending on options: runs BEM mode `generateBEM` or `generateOutput`.
3. Generated CSS pasts in new window in editor.

I describe only how `generateOutput` works because it's simple than `generateBEM`.
1. Function `generateOutput` get source HTML `self.source` and parsed for class names list with `class parser(HTMLParser)` (Python standard HTML parser).
2. Then with `for` loop each class name from the list added to `output`.

**Comment by Alexey-T** [comment]
просто для удобства портинга, удобно брать у вас work.py который имеет два def-a generate***. Чтобы не выискивать их.

**Comment by hudochenkov** [comment]
Я не буду усложнять код без надобности. Алгоритм расписан, исходники есть. При желании можно легко портировать куда угодно.

**Comment by Alexey-T** [comment]
ок. только обновлять один файл work.py удобно.
